// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/todos": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/todos" | "/*";
  };
  "routes/layout.tsx": {
    id: "routes/layout";
    page: "/" | "/todos";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/todos.tsx": {
    id: "routes/todos";
    page: "/todos";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/layout": typeof import("./app/routes/layout.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/todos": typeof import("./app/routes/todos.tsx");
  "routes/not-found": typeof import("./app/routes/not-found.tsx");
};